from django.contrib import admin
from django.urls import include, path

from core import portal_views
from core import console_views as console
from django.shortcuts import redirect

urlpatterns = [
    path("panel/devices/<int:pk>/buzzer/history/", console.buzzer_history, name="panel-buzzer-history"),
    path("panel/live/stream/", console.live_stream, name="panel-live-stream"),
    path("panel/connections/", console.connection_settings, name="panel-connections"),
    path("panel/devices/<int:pk>/buzzer/", console.buzzer_rules, name="panel-buzzer-list"),
    path("panel/devices/<int:pk>/buzzer/new/", console.buzzer_editor, name="panel-buzzer-create"),
    path("panel/devices/<int:pk>/buzzer/<int:rule_pk>/", console.buzzer_editor, name="panel-buzzer-edit"),
    path("panel/devices/<int:pk>/broker/rotate/", console.broker_rotate, name="panel-broker-rotate"),
    path("", lambda request: redirect("panel-dashboard")),
    path("setup/", console.setup, name="setup"),
    path("panel/devices/bulk/", console.device_bulk, name="panel-device-bulk"),
    path("panel/memberships/<int:pk>/edit/", console.membership_editor, name="panel-membership-edit"),
    path("panel/live/", console.dashboard_data, name="panel-live"),
    path("panel/devices/<int:pk>/preferences/", console.preferences, name="panel-preferences"),
    path("panel/data-sources/<int:pk>/refresh/", console.source_refresh, name="panel-source-refresh"),
    path("panel/companies/<int:pk>/edit/", console.company_editor, name="panel-company-edit"),
    path("panel/users/<int:pk>/edit/", console.user_editor, name="panel-user-edit"),
    path("panel/prices/", console.price_lists, name="panel-price-list"),
    path("panel/prices/new/", console.price_editor, name="panel-price-create"),
    path("panel/prices/<int:pk>/", console.price_detail, name="panel-price-detail"),
    path("panel/prices/<int:pk>/edit/", console.price_editor, name="panel-price-edit"),
    path("panel/prices/<int:pk>/items/new/", console.price_item_editor, name="panel-price-item-create"),
    path("panel/prices/<int:pk>/items/<int:item_pk>/", console.price_item_editor, name="panel-price-item-edit"),
    path("panel/settings/", console.settings_editor, name="panel-settings"),
    path("panel/integrations/", console.integrations, name="panel-integrations"),
    path("panel/integrations/new/", console.integration_editor, name="panel-integration-create"),
    path("panel/integrations/<int:pk>/", console.integration_editor, name="panel-integration-edit"),
    path("panel/plans/", console.rules, name="panel-rules"),
    path("panel/plans/<int:pk>/", console.rule_editor, name="panel-rule-edit"),
    path("panel/templates/", console.templates, name="panel-templates"),
    path("panel/templates/new/", console.template_editor, name="panel-template-create"),
    path("panel/templates/<int:pk>/", console.template_detail, name="panel-template-detail"),
    path("panel/templates/<int:pk>/edit/", console.template_editor, name="panel-template-edit"),
    path("panel/templates/<int:pk>/pages/new/", console.page_editor, name="panel-page-create"),
    path("panel/templates/<int:pk>/pages/<int:page_pk>/", console.page_editor, name="panel-page-edit"),
    path("panel/pages/<int:pk>/elements/new/", console.element_editor, name="panel-element-create"),
    path("panel/pages/<int:pk>/elements/<int:element_pk>/", console.element_editor, name="panel-element-edit"),
    path("panel/monitoring/", console.monitoring, name="panel-monitoring"),
    path("panel/monitoring/check/", console.check_services_now, name="panel-monitor-check"),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("panel/", portal_views.dashboard, name="panel-dashboard"),
    path("panel/devices/", portal_views.device_list, name="panel-device-list"),
    path("panel/devices/new/", portal_views.device_create, name="panel-device-create"),
    path("panel/devices/<int:pk>/", portal_views.device_detail, name="panel-device-detail"),
    path("panel/devices/<int:pk>/edit/", portal_views.device_edit, name="panel-device-edit"),
    path("panel/devices/<int:pk>/token/", portal_views.device_token_rotate, name="panel-device-token-rotate"),
    path("panel/devices/<int:pk>/token/success/", portal_views.device_token_success, name="panel-device-token-success"),
    path("panel/devices/<int:pk>/activation/", portal_views.device_activation_toggle, name="panel-device-activation-toggle"),
    path("panel/messages/", portal_views.message_list, name="panel-message-list"),
    path("panel/messages/new/", portal_views.message_create, name="panel-message-create"),
    path("panel/messages/<int:pk>/edit/", portal_views.message_edit, name="panel-message-edit"),
    path("panel/data-sources/", portal_views.data_source_list, name="panel-data-source-list"),
    path("panel/data-sources/new/", portal_views.data_source_create, name="panel-data-source-create"),
    path("panel/data-sources/<int:pk>/edit/", portal_views.data_source_edit, name="panel-data-source-edit"),
    path("panel/firmware/", portal_views.firmware_list, name="panel-firmware-list"),
    path("panel/firmware/upload/", portal_views.firmware_upload, name="panel-firmware-upload"),
    path("panel/companies/", portal_views.company_list, name="panel-company-list"),
    path("panel/companies/new/", portal_views.company_create, name="panel-company-create"),
    path("panel/users/", portal_views.user_list, name="panel-user-list"),
    path("panel/users/new/", portal_views.user_create, name="panel-user-create"),
    path("panel/memberships/", portal_views.membership_list, name="panel-membership-list"),
    path("panel/memberships/new/", portal_views.membership_create, name="panel-membership-create"),
    path("api/v1/", include("core.urls")),
]
