from django.contrib import admin
from django.urls import include, path

from core import portal_views
from core import console_views as console
from core import studio_views as studio
from django.shortcuts import redirect

urlpatterns = [
    path("panel/studio/", studio.home, name="panel-studio"),
    path("panel/studio/profiles/new/", studio.profile_editor, name="panel-profile-create"),
    path("panel/studio/profiles/<int:pk>/", studio.profile_editor, name="panel-profile-edit"),
    path("panel/studio/cities/new/", studio.city_editor, name="panel-city-create"),
    path("panel/studio/cities/<int:pk>/", studio.city_editor, name="panel-city-edit"),
    path("panel/studio/assets/new/", studio.asset_upload, name="panel-asset-upload"),
    path("panel/studio/assets/<int:pk>/", studio.asset_preview, name="panel-asset-preview"),
    path("panel/studio/new/", studio.template_create, name="panel-studio-create"),
    path("panel/studio/<int:pk>/", studio.editor, name="panel-studio-editor"),
    path("panel/studio/<int:pk>/save/", studio.save_draft, name="panel-studio-save"),
    path("panel/studio/<int:pk>/publish/", studio.publish, name="panel-studio-publish"),
    path("panel/studio/assignments/new/", studio.assignment_editor, name="panel-assignment-create"),
    path("panel/studio/assignments/<int:pk>/", studio.assignment_editor, name="panel-assignment-edit"),
    path("panel/devices/<int:pk>/simulator/", studio.simulator, name="panel-studio-simulator"),
    path("panel/devices/<int:pk>/display-manifest/", studio.simulator_manifest, name="panel-studio-manifest"),
    path("panel/devices/<int:pk>/display-prices/<int:list_pk>/", studio.simulator_prices, name="panel-studio-price-page"),
    path("panel/devices/<int:pk>/display-preferences/", studio.preferences, name="panel-studio-preferences"),
    path("panel/devices/<int:pk>/chart-preferences/", studio.chart_preferences, name="panel-chart-preferences"),
    path("panel/devices/<int:pk>/receipts/", studio.receipts, name="panel-device-receipts"),
    path("panel/data-sources/<int:pk>/fields/", studio.source_fields, name="panel-source-fields"),
    path("panel/data-sources/<int:pk>/fields/new/", studio.field_editor, name="panel-source-field-create"),
    path("panel/data-sources/<int:pk>/fields/<int:field_pk>/", studio.field_editor, name="panel-source-field-edit"),
    path("panel/data-sources/<int:pk>/discover/", studio.discover_fields, name="panel-source-discover"),
    path("panel/prices/<int:pk>/import/", studio.excel_upload, name="panel-price-import"),
    path("panel/prices/<int:pk>/import/<uuid:batch_id>/", studio.import_mapping, name="panel-price-import-map"),
    path("panel/prices/<int:pk>/releases/", studio.releases, name="panel-price-releases"),
    path("panel/operations/", studio.operations, name="panel-operations"),
    path("panel/operations/backup/", studio.backup_now, name="panel-backup-now"),
    path("panel/operations/backup/<uuid:job_id>/", studio.backup_download, name="panel-backup-download"),
    path("panel/users/<int:pk>/access/", console.user_access, name="panel-user-access"),
    path("panel/devices/<int:pk>/buzzer/history/", console.buzzer_history, name="panel-buzzer-history"),
    path("panel/live/stream/", console.live_stream, name="panel-live-stream"),
    path("panel/connections/", console.connection_settings, name="panel-connections"),
    path("panel/devices/<int:pk>/buzzer/", console.buzzer_rules, name="panel-buzzer-list"),
    path("panel/devices/<int:pk>/buzzer/new/", console.buzzer_editor, name="panel-buzzer-create"),
    path("panel/devices/<int:pk>/buzzer/<int:rule_pk>/", console.buzzer_editor, name="panel-buzzer-edit"),
    path("panel/devices/<int:pk>/broker/rotate/", console.broker_rotate, name="panel-broker-rotate"),
    path("", lambda request: redirect("panel-dashboard")),
    path("setup/", console.setup, name="setup"),
    path("panel/devices/bulk/", console.device_bulk, name="panel-device-bulk"),
    path("panel/memberships/<int:pk>/edit/", console.membership_editor, name="panel-membership-edit"),
    path("panel/live/", console.dashboard_data, name="panel-live"),
    path("panel/devices/<int:pk>/preferences/", console.preferences, name="panel-preferences"),
    path("panel/data-sources/<int:pk>/refresh/", console.source_refresh, name="panel-source-refresh"),
    path("panel/companies/<int:pk>/edit/", console.company_editor, name="panel-company-edit"),
    path("panel/users/<int:pk>/edit/", console.user_editor, name="panel-user-edit"),
    path("panel/prices/", console.price_lists, name="panel-price-list"),
    path("panel/prices/new/", console.price_editor, name="panel-price-create"),
    path("panel/prices/<int:pk>/", console.price_detail, name="panel-price-detail"),
    path("panel/prices/<int:pk>/edit/", console.price_editor, name="panel-price-edit"),
    path("panel/prices/<int:pk>/items/new/", console.price_item_editor, name="panel-price-item-create"),
    path("panel/prices/<int:pk>/items/<int:item_pk>/", console.price_item_editor, name="panel-price-item-edit"),
    path("panel/settings/", console.settings_editor, name="panel-settings"),
    path("panel/integrations/", console.integrations, name="panel-integrations"),
    path("panel/integrations/new/", console.integration_editor, name="panel-integration-create"),
    path("panel/integrations/<int:pk>/", console.integration_editor, name="panel-integration-edit"),
    path("panel/plans/", console.rules, name="panel-rules"),
    path("panel/plans/<int:pk>/", console.rule_editor, name="panel-rule-edit"),
    path("panel/templates/", console.templates, name="panel-templates"),
    path("panel/templates/new/", console.template_editor, name="panel-template-create"),
    path("panel/templates/<int:pk>/", console.template_detail, name="panel-template-detail"),
    path("panel/templates/<int:pk>/edit/", console.template_editor, name="panel-template-edit"),
    path("panel/templates/<int:pk>/pages/new/", console.page_editor, name="panel-page-create"),
    path("panel/templates/<int:pk>/pages/<int:page_pk>/", console.page_editor, name="panel-page-edit"),
    path("panel/pages/<int:pk>/elements/new/", console.element_editor, name="panel-element-create"),
    path("panel/pages/<int:pk>/elements/<int:element_pk>/", console.element_editor, name="panel-element-edit"),
    path("panel/monitoring/", console.monitoring, name="panel-monitoring"),
    path("panel/monitoring/check/", console.check_services_now, name="panel-monitor-check"),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("panel/", portal_views.dashboard, name="panel-dashboard"),
    path("panel/devices/", portal_views.device_list, name="panel-device-list"),
    path("panel/devices/new/", portal_views.device_create, name="panel-device-create"),
    path("panel/devices/<int:pk>/", portal_views.device_detail, name="panel-device-detail"),
    path("panel/devices/<int:pk>/edit/", portal_views.device_edit, name="panel-device-edit"),
    path("panel/devices/<int:pk>/token/", portal_views.device_token_rotate, name="panel-device-token-rotate"),
    path("panel/devices/<int:pk>/token/success/", portal_views.device_token_success, name="panel-device-token-success"),
    path("panel/devices/<int:pk>/activation/", portal_views.device_activation_toggle, name="panel-device-activation-toggle"),
    path("panel/messages/", portal_views.message_list, name="panel-message-list"),
    path("panel/messages/new/", portal_views.message_create, name="panel-message-create"),
    path("panel/messages/<int:pk>/edit/", portal_views.message_edit, name="panel-message-edit"),
    path("panel/data-sources/", portal_views.data_source_list, name="panel-data-source-list"),
    path("panel/data-sources/new/", portal_views.data_source_create, name="panel-data-source-create"),
    path("panel/data-sources/<int:pk>/edit/", portal_views.data_source_edit, name="panel-data-source-edit"),
    path("panel/firmware/", portal_views.firmware_list, name="panel-firmware-list"),
    path("panel/firmware/upload/", portal_views.firmware_upload, name="panel-firmware-upload"),
    path("panel/companies/", portal_views.company_list, name="panel-company-list"),
    path("panel/companies/new/", portal_views.company_create, name="panel-company-create"),
    path("panel/users/", portal_views.user_list, name="panel-user-list"),
    path("panel/users/new/", portal_views.user_create, name="panel-user-create"),
    path("panel/memberships/", portal_views.membership_list, name="panel-membership-list"),
    path("panel/memberships/new/", portal_views.membership_create, name="panel-membership-create"),
    path("api/v1/", include("core.urls")),
]
