# Generated by Django 5.1.2 on 2026-09-23 22:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_device_config_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='گجت من', max_length=100)),
                ('public_base_url', models.URLField(blank=True)),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=64)),
                ('setup_complete', models.BooleanField(default=False)),
                ('heartbeat_timeout', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(30)])),
                ('audit_retention_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('test_mode', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=64, unique=True)),
                ('cpu_percent', models.FloatField(null=True)),
                ('memory_bytes', models.BigIntegerField(null=True)),
                ('disk_bytes', models.BigIntegerField(null=True)),
                ('network_rx_bytes', models.BigIntegerField(null=True)),
                ('network_tx_bytes', models.BigIntegerField(null=True)),
                ('sampled_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(default='collector', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='devicestatus',
            name='battery_level',
        ),
        migrations.AddField(
            model_name='company',
            name='account_kind',
            field=models.CharField(choices=[('personal', 'شخصی'), ('business', 'شرکت / نمایندگی')], default='business', max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='core.company'),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='category',
            field=models.CharField(choices=[('price', 'قیمت'), ('news', 'اخبار'), ('weather', 'آب\u200cوهوا'), ('text', 'متن')], default='price', max_length=16),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='extraction_pattern',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='last_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='ttl_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='unit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='last_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='planrule',
            name='can_send_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planrule',
            name='max_telegram_sources',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planrule',
            name='min_refresh_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='wordpressdevice',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordpressdevice',
            name='customer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wordpressdevice',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wordpressdevice',
            name='recipient_contact',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wordpressdevice',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Platform owner'), ('employee', 'Internal employee'), ('company_admin', 'Company admin'), ('company_operator', 'Company operator'), ('member', 'کاربر دستگاه')], max_length=32),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_data_sources', to='core.company'),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='endpoint_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='source_type',
            field=models.CharField(choices=[('http', 'HTTP API'), ('telegram', 'Telegram'), ('rss', 'RSS Feed'), ('internal', 'Internal data'), ('web', 'صفحه وب')], default='http', max_length=64),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('object_label', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('navy', 'سرمه\u200cای'), ('light', 'روشن'), ('carbon', 'کربن')], default='navy', max_length=16)),
                ('rotation_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(86400)])),
                ('live_updates', models.BooleanField(default=True)),
                ('custom_primary', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'رنگ را با فرمت #RRGGBB وارد کنید.')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.wordpressdevice')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('wordpress', 'WordPress'), ('mqtt', 'MQTT'), ('telegram', 'تلگرام'), ('provider', 'منبع داده'), ('monitor', 'پایش سرور'), ('notifications', 'اعلان\u200cها'), ('metrics', 'توکن پایش')], max_length=24)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('port', models.PositiveIntegerField(default=8883, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('use_tls', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('encrypted_secret', models.TextField(blank=True, editable=False)),
                ('encrypted_webhook_secret', models.TextField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='core.company')),
                ('target_devices', models.ManyToManyField(blank=True, related_name='price_lists', to='core.wordpressdevice')),
            ],
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.pricelist'),
        ),
        migrations.CreateModel(
            name='CampaignDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.messagecampaign')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wordpressdevice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'device'), name='unique_campaign_delivery')],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='تومان', max_length=32)),
                ('valid_until', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pricelist')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('price_list', 'code'), name='unique_price_item_code')],
            },
        ),
        migrations.CreateModel(
            name='SourceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_selections', to='core.wordpressdevice')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.externaldatasource')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('device', 'source'), name='unique_device_source')],
            },
        ),
    ]
