# Generated by Django 5.1.2 on 2026-09-23 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_platformsettings_resourcesnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='externaldatasource',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('display_key',), name='unique_global_source_key'),
        ),
    ]
