# Generated by Django 5.1.2 on 2026-09-24 08:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_initialize_new_plan_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldatasource',
            name='disposable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='encrypted_push_secret',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='update_mode',
            field=models.CharField(choices=[('periodic', 'دریافت دوره\u200cای'), ('push', 'لحظه\u200cای؛ دریافت Webhook')], default='periodic', max_length=16),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='disposable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='cleanup_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='device_heartbeat_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='device_mqtt_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='device_mqtt_path',
            field=models.CharField(default='/mqtt', max_length=128),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='device_mqtt_port',
            field=models.PositiveIntegerField(default=443, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='device_mqtt_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='device_mqtt_transport',
            field=models.CharField(choices=[('websockets', 'WebSocket امن'), ('tcp', 'MQTT TCP')], default='websockets', max_length=16),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='managed_tls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='wordpress_poll_seconds',
            field=models.PositiveIntegerField(default=900, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='wordpress_signature_max_age',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='disposable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BuzzerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('all', 'همه اطلاعات'), ('source', 'یک منبع'), ('price', 'قیمت یک کالا'), ('messages', 'پیام\u200cهای شرکت')], default='all', max_length=16)),
                ('trigger', models.CharField(choices=[('new', 'اطلاعات جدید یا تغییر مقدار'), ('percent', 'نوسان درصدی'), ('absolute', 'نوسان به مقدار مشخص'), ('above', 'عبور از سقف'), ('below', 'عبور از کف')], default='new', max_length=16)),
                ('direction', models.CharField(choices=[('both', 'افزایش و کاهش'), ('up', 'فقط افزایش'), ('down', 'فقط کاهش')], default='both', max_length=8)),
                ('threshold', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('window_seconds', models.PositiveIntegerField(default=0)),
                ('notify_first', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(3000)])),
                ('repeat', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('gap_ms', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(3000)])),
                ('cooldown_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(86400)])),
                ('max_per_hour', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('last_triggered_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzer_rules', to='core.wordpressdevice')),
                ('price_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.priceitem')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.externaldatasource')),
            ],
        ),
        migrations.CreateModel(
            name='BuzzerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('item_key', models.CharField(max_length=150)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buzzer_events', to='core.wordpressdevice')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.buzzerrule')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceBrokerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_password', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_credential', to='core.wordpressdevice')),
            ],
        ),
    ]
