# Generated by Django 5.1.2 on 2026-09-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_externaldatasource_disposable_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='buzzerevent',
            index=models.Index(fields=['device', 'expires_at'], name='buzzer_device_expiry'),
        ),
        migrations.AddIndex(
            model_name='buzzerevent',
            index=models.Index(fields=['rule', 'created_at'], name='buzzer_rule_time'),
        ),
    ]
