# Generated by Django 5.1.2 on 2026-09-29 10:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_staffaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='ایران', max_length=60)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='display-assets/%Y/%m/')),
                ('kind', models.CharField(choices=[('image', 'تصویر'), ('font', 'فونت')], max_length=16)),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField(default=480, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(1920)])),
                ('height', models.PositiveIntegerField(default=320, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(1920)])),
                ('diagonal_inches', models.DecimalField(decimal_places=1, default=3.5, max_digits=4)),
                ('max_elements', models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_chart_points', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(500)])),
                ('supports_glow', models.BooleanField(default=False)),
                ('supports_animation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('backup', 'پشتیبان'), ('sms', 'پیامک')], max_length=16)),
                ('key', models.CharField(max_length=180, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt', models.DateTimeField()),
                ('lease_until', models.DateTimeField(null=True)),
                ('result', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_seconds', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(3600)])),
                ('items_per_page', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('item_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3600)])),
                ('resume_seconds', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(3600)])),
                ('automatic', models.BooleanField(default=True)),
                ('touch_short', models.CharField(choices=[('next_batch', 'دسته بعد'), ('next_page', 'صفحه بعد'), ('previous_batch', 'دسته قبل'), ('previous_page', 'صفحه قبل'), ('details', 'جزئیات کالا')], default='next_batch', max_length=20)),
                ('touch_long', models.CharField(choices=[('next_batch', 'دسته بعد'), ('next_page', 'صفحه بعد'), ('previous_batch', 'دسته قبل'), ('previous_page', 'صفحه قبل'), ('details', 'جزئیات کالا')], default='next_page', max_length=20)),
                ('charts', models.JSONField(blank=True, default=dict)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_preferences', to='core.wordpressdevice')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('page', 'صفحه'), ('fallback', 'جایگزین مقدار'), ('offline', 'قطع ارتباط'), ('boot', 'شروع')], default='page', max_length=16)),
                ('draft', models.JSONField(blank=True, default=dict)),
                ('draft_revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.displayprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('document', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.displaytemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'عمومی'), ('plan', 'پلن'), ('company', 'شرکت'), ('user', 'کاربر'), ('device', 'دستگاه')], max_length=12)),
                ('plan', models.CharField(blank=True, choices=[('simple', 'ساده'), ('pro', 'VIP')], max_length=8)),
                ('position', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wordpressdevice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.displayversion')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rows', models.JSONField()),
                ('columns', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pricelist')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('backup_enabled', models.BooleanField(default=False)),
                ('backup_hours', models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)])),
                ('next_backup', models.DateTimeField(blank=True, null=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_recipient', models.CharField(blank=True, max_length=100)),
                ('sms_recipient_key', models.CharField(default='to', max_length=64)),
                ('sms_message_key', models.CharField(default='message', max_length=64)),
                ('sms_template', models.TextField(default='Gadget: {service}: {state}')),
                ('weather_url', models.CharField(blank=True, max_length=500)),
                ('weather_value_path', models.CharField(default='current.temperature_2m', max_length=255)),
                ('weather_condition_path', models.CharField(blank=True, max_length=255)),
                ('weather_unit', models.CharField(default='°C', max_length=32)),
                ('weather_seconds', models.PositiveIntegerField(default=900, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)])),
                ('sms_integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.integration')),
                ('weather_integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.integration')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('items', models.JSONField(default=list)),
                ('scheduled_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='core.pricelist')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('unit', models.CharField(max_length=32)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.priceitem')),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pricerelease')),
            ],
        ),
        migrations.CreateModel(
            name='SourceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('numeric', models.BooleanField(default=False)),
                ('keep_history', models.BooleanField(default=False)),
                ('timestamp_path', models.CharField(blank=True, max_length=255)),
                ('open_path', models.CharField(blank=True, max_length=255)),
                ('high_path', models.CharField(blank=True, max_length=255)),
                ('low_path', models.CharField(blank=True, max_length=255)),
                ('close_path', models.CharField(blank=True, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fields', to='core.externaldatasource')),
            ],
        ),
        migrations.CreateModel(
            name='MarketSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=24)),
                ('ohlc', models.JSONField(blank=True, default=dict)),
                ('origin', models.CharField(default='sample', max_length=12)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='core.sourcefield')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=64)),
                ('manifest', models.JSONField()),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_receipts', to='core.wordpressdevice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device', 'revision'), name='unique_device_receipt')],
            },
        ),
        migrations.AddConstraint(
            model_name='displayversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='unique_display_version'),
        ),
        migrations.AddConstraint(
            model_name='pricerelease',
            constraint=models.UniqueConstraint(fields=('price_list', 'number'), name='unique_price_release'),
        ),
        migrations.AddIndex(
            model_name='productsample',
            index=models.Index(fields=['item', 'observed_at'], name='core_produc_item_id_5c1c63_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcefield',
            constraint=models.UniqueConstraint(fields=('source', 'key'), name='unique_source_field'),
        ),
        migrations.AddIndex(
            model_name='marketsample',
            index=models.Index(fields=['field', 'observed_at'], name='core_market_field_i_a02044_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketsample',
            constraint=models.UniqueConstraint(fields=('field', 'observed_at'), name='unique_market_sample'),
        ),
    ]
