# Generated by Django 5.2.17 on 2026-09-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_city_displayasset_displayprofile_operationalalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefield',
            name='provider_timeframe_seconds',
            field=models.PositiveIntegerField(choices=[(0, 'بدون کندل آماده'), (60, '۱ دقیقه'), (300, '۵ دقیقه'), (900, '۱۵ دقیقه'), (3600, '۱ ساعت'), (14400, '۴ ساعت'), (86400, '۱ روز')], default=0),
        ),
    ]
