# Generated by Django 5.2.17 on 2026-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sourcefield_provider_timeframe_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaypreference',
            name='touch_long',
            field=models.CharField(choices=[('next_batch', 'دسته بعد'), ('next_page', 'صفحه بعد'), ('previous_batch', 'دسته قبل'), ('previous_page', 'صفحه قبل')], default='next_page', max_length=20),
        ),
        migrations.AlterField(
            model_name='displaypreference',
            name='touch_short',
            field=models.CharField(choices=[('next_batch', 'دسته بعد'), ('next_page', 'صفحه بعد'), ('previous_batch', 'دسته قبل'), ('previous_page', 'صفحه قبل')], default='next_batch', max_length=20),
        ),
    ]
