# Generated by Django 5.2.17 on 2026-09-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_displaypreference_touch_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayasset',
            name='animated',
            field=models.BooleanField(default=False),
        ),
    ]
